# PR Labeler Configuration
# Automatically labels pull requests based on files changed and branch names
# Reference: https://github.com/actions/labeler

# Versioning and releases
'🏷️ version':
  - changed-files:
    - any-glob-to-any-file: ['VERSION', '.github/scripts/version.sh', '.github/workflows/release.yml', '.github/workflows/auto-tag.yml']

# Documentation
'📝 documentation':
  - changed-files:
    - any-glob-to-any-file: ['**/*.md', 'docs/**/*', '**/*.mdx']

# Workflows and CI/CD
'🔄 workflow':
  - changed-files:
    - any-glob-to-any-file: ['.github/workflows/**/*', '.github/actions/**/*', '.github/labeler.yml']

# Configuration files
'⚙️ configuration':
  - changed-files:
    - any-glob-to-any-file: ['**/*.yaml', '**/*.yml', '**/*.toml', '**/*.config.*', '**/package.yaml', '.github/labels.json']

# AUR Package files
'📦 package':
  - changed-files:
    - any-glob-to-any-file: ['**/PKGBUILD', '**/.SRCINFO', 'packages/**/*']

# Tests (if any test files are added in the future)
'🧪 tests':
  - changed-files:
    - any-glob-to-any-file: ['**/*test*', '**/*spec*', '**/tests/**/*']

# Branch-based labels (matching the repository's branching strategy)
'👍 new':
  - head-branch: ['^package/']

'✨ feature':
  - head-branch: ['^feat/', '^feature/']

'🐛 bug':
  - head-branch: ['^fix/', '^bugfix/']

'🚑 hotfix':
  - head-branch: ['^hotfix/']

'♻️ refactor':
  - head-branch: ['^refactor/']

'⚡ performance':
  - head-branch: ['^perf/', '^performance/']

'🔒 security':
  - head-branch: ['^security/', '^sec/']
  - changed-files:
    - any-glob-to-any-file: ['**/*security*', '**/*auth*', '**/*encrypt*']

'🤖 copilot':
  - head-branch: ['^copilot/']

'🤖 renovate':
  - head-branch: ['^package/renovate-']
