name: Build and Security Analysis

on:
  workflow_call:

jobs:
  build:
    name: Build ESP32 Project
    uses: ./.github/workflows/build.yml
    permissions:
      contents: read

  security-analysis:
    name: CodeQL Security Analysis
    uses: ./.github/workflows/codeql.yml
    permissions:
      actions: read
      contents: read
      security-events: write
