name: Build and Security Analysis

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # Run every Monday at 00:00 UTC
    - cron: '0 0 * * 1'

jobs:
  build:
    name: Build ESP32 Project
    uses: ./.github/workflows/build.yml
    permissions:
      contents: read

  security-analysis:
    name: CodeQL Security Analysis
    uses: ./.github/workflows/codeql.yml
    permissions:
      actions: read
      contents: read
      security-events: write
