name: Build and Security Analysis

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # Run every Monday at 00:00 UTC
    - cron: '0 0 * * 1'

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: cpp
        queries: security-and-quality
    
    - name: Setup ESP-IDF
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: v5.1.2
        target: esp32s3
        path: '.'
    
    - name: Create config.h from example
      run: |
        cp main/config.h.example main/config.h
    
    - name: Build project
      run: |
        . $IDF_PATH/export.sh
        idf.py set-target esp32s3
        # Pass WiFi credentials as compiler definitions for CI build
        # This allows the build to succeed without exposing real credentials
        idf.py -DCMAKE_C_FLAGS='-DWIFI_SSID=\"test_ssid\" -DWIFI_PASS=\"test_password\"' build
    
    - name: Archive build artifacts
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: |
          build/*.bin
          build/*.elf
          build/*.map
        retention-days: 30
    
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
      with:
        category: "/language:cpp"
