name: Build ESP32 Project (Deprecated)

# This workflow has been replaced by:
# - pr-checks.yml (for pull requests)
# - main-release-checks.yml (for main/release branches)
# 
# This file is kept for backward compatibility and will be removed in a future update.

on:
  push:
    branches: [ develop ]  # Only trigger on develop branch now
  workflow_dispatch:  # Allow manual triggers

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    
    - name: Build with ESP-IDF
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: v5.1.2
        target: esp32s3
        path: '.'
    
    - name: Archive build artifacts
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: |
          build/*.bin
          build/*.elf
          build/*.map
        retention-days: 30
