name: Static Code Analysis

on:
  push:
    branches: [ main, release ]
  pull_request:
    branches: [ main, release ]
  workflow_call:
    inputs:
      artifact_retention_days:
        description: 'Number of days to retain artifacts'
        required: false
        type: number
        default: 30

jobs:
  cppcheck:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install cppcheck
      run: |
        sudo apt-get update
        sudo apt-get install -y cppcheck

    - name: Run cppcheck
      run: |
        cppcheck --enable=all \
          --suppress=missingIncludeSystem \
          --suppress=unusedFunction \
          --suppress=unmatchedSuppression \
          --inline-suppr \
          --error-exitcode=1 \
          --std=c11 \
          --platform=unix32 \
          -I main \
          main/*.c \
          2>&1 | tee cppcheck-report.txt
      continue-on-error: true

    - name: Upload cppcheck report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: cppcheck-report
        path: cppcheck-report.txt
        retention-days: ${{ inputs.artifact_retention_days || 30 }}
